name: Build and Deploy

on:
  push:
    branches:
      - main # 或者你的默认开发分支
  # 允许你从 Actions 选项卡手动运行此工作流程
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          npm install
          # 如果是其他构建工具，比如 Maven, Gradle, 替换上面的命令
      - name: Build
        run: npm run docs:build # 如果是其他构建命令，替换上面的命令
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./.vitepress/dist
      - name: Deploy via SSH
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-avz --delete"
          SOURCE: "./.vitepress/dist/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }} # 默认是 ssh 端口，可以不填
          TARGET: "/home/nginx/vitepress" # 服务器上的目标路径

